import { SiteContent } from '../types';

export const defaultContent: SiteContent = {
  header_title: "Black Prados K9",
  header_tagline: "Wild to Wise",
  hero_eyebrow: "Boarding & Training, Under One Roof",
  hero_title: "Wild to wise.",
  hero_sub: "Overnight boarding with real yard time, and training programs built by certified handlers — not a kennel that also takes commands.",
  hero_cta_book: "Book a stay",
  hero_cta_plans: "See training plans",
  stat_num_1: "14",
  stat_label_1: "Years running",
  stat_num_2: "2 acres",
  stat_label_2: "Fenced play yard",
  stat_num_3: "1:4",
  stat_label_3: "Handler to dog ratio",
  stat_num_4: "98%",
  stat_label_4: "Rebooking rate",

  boarding_cmd: "Boarding",
  boarding_heading: "Overnight stays, zero cage time.",
  boarding_sub: "Every stay includes three yard sessions a day, a private suite, and a daily photo update — no add-on required. Payment by GPay or cash, settled directly with us — no online checkout.",
  board_card_cmd_1: "Standard Suite",
  board_card_title_1: "The Den",
  board_card_desc_1: "A private indoor-outdoor suite with raised bedding, three yard sessions, and twice-daily feeding to your schedule.",
  board_card_price_1: "₹700",
  board_card_cmd_2: "Most Booked",
  board_card_title_2: "The Pack Suite",
  board_card_desc_2: "Everything in The Den, plus supervised group play with dogs matched to your dog's energy and size.",
  board_card_price_2: "₹950",
  board_card_cmd_3: "Extended Stay",
  board_card_title_3: "The Homestead",
  board_card_desc_3: "For stays over a week: a dedicated handler, one-on-one enrichment time, and a nightly video call if you want it.",
  board_card_price_3: "₹1,300",
  board_tag_0: "Daily photo update",
  board_tag_1: "Climate-controlled suites",
  board_tag_2: "Own bedding welcome",
  board_tag_3: "Medication administration",
  board_tag_4: "Vet on call",

  training_cmd: "Training",
  training_heading: "Programs that travel home with you.",
  training_sub: "Every program ends with a handler session — we teach you the cues, not just the dog.",
  train_row_cmd_1: "Puppy",
  train_row_title_1: "Foundations",
  train_row_desc_1: "Crate manners, name recognition, and the first commands — for pups 8 to 20 weeks.",
  train_row_cmd_2: "Obedience",
  train_row_title_2: "House Manners",
  train_row_desc_2: "Sit, stay, heel, and recall, reinforced on-leash and off, in the house and out in the yard.",
  train_row_cmd_3: "Behavior",
  train_row_title_3: "Reactivity & Anxiety",
  train_row_desc_3: "One-on-one work for leash reactivity, separation anxiety, and resource guarding, at the dog's pace.",
  train_row_cmd_4: "Advanced",
  train_row_title_4: "Off-Leash Reliability",
  train_row_desc_4: "Distance commands, distraction-proofing, and real-world recall for dogs ready to go off-leash.",

  train_step_num_1: "Step 1",
  train_step_title_1: "Assessment",
  train_step_desc_1: "A free 30-minute evaluation to set a baseline and pick the right program.",
  train_step_num_2: "Step 2",
  train_step_title_2: "Daily sessions",
  train_step_desc_2: "Short, focused sessions — dogs learn faster in bursts than marathons.",
  train_step_num_3: "Step 3",
  train_step_title_3: "Real-world reps",
  train_step_desc_3: "Commands practiced in the yard, on walks, and around distractions.",
  train_step_num_4: "Step 4",
  train_step_title_4: "Handler session",
  train_step_desc_4: "You come in and run the commands yourself, coached by the trainer.",
  train_step_num_5: "Step 5",
  train_step_title_5: "30-day follow-up",
  train_step_desc_5: "A check-in call to troubleshoot anything that's slipping at home.",

  grooming_cmd: "Grooming",
  grooming_heading: "Wash, trim, and looking sharp.",
  grooming_sub: "Every groom is handled by one groomer start to finish, so your dog isn't passed station to station. Payment by GPay or cash on the day.",
  groom_card_cmd_1: "Quick Service",
  groom_card_title_1: "Wash & Go",
  groom_card_desc_1: "Bath with breed-appropriate shampoo, blow-dry, brush-out, ear cleaning, and nail trim.",
  groom_card_price_1: "₹600",
  groom_card_cmd_2: "Most Booked",
  groom_card_title_2: "Full Groom",
  groom_card_desc_2: "Everything in Wash & Go, plus a breed-standard or custom haircut and a light finishing spritz.",
  groom_card_price_2: "₹1,200",
  groom_card_cmd_3: "Deep Treatment",
  groom_card_title_3: "Spa Package",
  groom_card_desc_3: "Full groom plus deep-conditioning treatment, teeth brushing, and paw balm for cracked pads.",
  groom_card_price_3: "₹1,800",

  groom_step_num_1: "Step 1",
  groom_step_title_1: "Check-in",
  groom_step_desc_1: "A quick look at skin, coat, and ears before we start.",
  groom_step_num_2: "Step 2",
  groom_step_title_2: "Bath & dry",
  groom_step_desc_2: "Breed-appropriate shampoo, hand-dried — no cage dryers.",
  groom_step_num_3: "Step 3",
  groom_step_title_3: "Trim & style",
  groom_step_desc_3: "Breed-standard or custom cut, done by hand and clipper.",
  groom_step_num_4: "Step 4",
  groom_step_title_4: "Nails & ears",
  groom_step_desc_4: "Trim, file, and clean — the parts most dogs hate, done fast.",
  groom_step_num_5: "Step 5",
  groom_step_title_5: "Finishing touch",
  groom_step_desc_5: "Brush-out, light spritz, and a bandana if your dog will tolerate it.",

  daycare_cmd: "Day Care",
  daycare_heading: "Drop off tired, pick up happy.",
  daycare_sub: "Dogs are grouped by size and energy, with a handler in every play yard — never left to a camera. Payment by GPay or cash on drop-off.",
  daycare_card_cmd_1: "Single Visit",
  daycare_card_title_1: "Half Day",
  daycare_card_desc_1: "Up to 5 hours of supervised group play, rest breaks, and fresh water on demand.",
  daycare_card_price_1: "₹450",
  daycare_card_cmd_2: "Most Booked",
  daycare_card_title_2: "Full Day",
  daycare_card_desc_2: "Drop off in the morning, pick up by close — group play, rest, and a midday enrichment activity.",
  daycare_card_price_2: "₹650",
  daycare_card_cmd_3: "Regulars",
  daycare_card_title_3: "Weekly Pass",
  daycare_card_desc_3: "Five full days, use them anytime in a rolling 30-day window. Ideal for work-week regulars.",
  daycare_card_price_3: "₹2,800",

  daycare_row_cmd_1: "7:00 AM",
  daycare_row_title_1: "Drop-off",
  daycare_row_desc_1: "Quick temperature and temperament check-in before your dog joins the yard.",
  daycare_row_cmd_2: "8:30 AM",
  daycare_row_title_2: "Group play",
  daycare_row_desc_2: "Free play in size- and energy-matched groups, always with a handler in the yard.",
  daycare_row_cmd_3: "12:00 PM",
  daycare_row_title_3: "Rest & enrichment",
  daycare_row_desc_3: "A quiet break with puzzle feeders and chew time to reset energy for the afternoon.",
  daycare_row_cmd_4: "3:30 PM",
  daycare_row_title_4: "Second play session",
  daycare_row_desc_4: "A shorter round of group play before wind-down.",
  daycare_row_cmd_5: "5:30 PM",
  daycare_row_title_5: "Pick-up window",
  daycare_row_desc_5: "A quick note home on how your dog's day went — energy, appetite, anything to watch.",

  gallery_cmd: "Gallery",
  gallery_heading: "A look inside the yard.",
  gallery_sub: "Photos from boarding stays, training sessions, groom days, and the play yard.",
  gallery_note: "Photos coming soon — send over your favorites and we'll drop them straight in.",

  testimonial_quote: "We boarded our reactive rescue for two weeks expecting the worst. He came home calmer than we'd ever seen him — and actually knew 'leave it.'",
  testimonial_author: "— Marisol T., boarded & trained a rescue shepherd mix",

  feedback_cmd: "Feedback",
  feedback_heading: "What owners are saying.",

  about_cmd: "About",
  about_p1: "Black Prados K9 started in a converted barn in 2011, because our founder — a certified trainer — got tired of dropping her own dog at kennels that were just cages with a yard attached.",
  about_p2: "Every handler on staff is certified in canine first aid and completes a 6-month apprenticeship under a lead trainer before working solo. Dogs are grouped by temperament, not just size, and every group play session is supervised, never left to a camera.",
  about_p3: "We keep it small on purpose. Capping intake means every dog gets seen, not just fed and let out.",
  about_stat_num_1: "6",
  about_stat_label_1: "Certified handlers on staff",
  about_stat_num_2: "40",
  about_stat_label_2: "Max dogs on site",
  about_stat_num_3: "3x",
  about_stat_label_3: "Daily yard sessions",
  about_stat_num_4: "24/7",
  about_stat_label_4: "On-site supervision",

  contact_cmd: "Contact",
  contact_heading: "Let's meet your dog.",
  contact_sub: "Every new dog starts with a free meet-and-greet, so we can match them to the right group before any stay or session.",
  contact_info_label_1: "Address",
  contact_info_val_1: "4420 Orchard Run Rd, Thrissur",
  contact_info_label_2: "Phone",
  contact_info_val_2: "(555) 019-2847",
  contact_info_label_3: "Hours",
  contact_info_val_3: "Mon–Sat, 7am–7pm",
  contact_info_label_4: "Drop-off",
  contact_info_val_4: "By appointment only",
  contact_info_label_5: "Payment",
  contact_info_val_5: "GPay or cash — paid directly, no online checkout",
};
